local ch = CPLUS.CHALLENGES.new_challenge("example_challenge", {
	name = "example_name",
	author = "example_author",
	version = "1.0.0",
}, {
	rules = {
		custom = {
			--{id = 'no_reward'},
			{ id = "no_reward_specific", value = "Big" },
			{ id = "no_extra_hand_money" },
			{ id = "no_interest" },
			{ id = "test", value = "aboba" },
		},
		modifiers = {
			{ id = "dollars", value = 100 },
			{ id = "discards", value = 1 },
			{ id = "hands", value = 6 },
			{ id = "reroll_cost", value = 10 },
			{ id = "joker_slots", value = 8 },
			{ id = "consumable_slots", value = 3 },
			{ id = "hand_size", value = 5 },
		},
	},
	jokers = {
		{ id = "j_egg" },
		{ id = "j_egg" },
		{ id = "j_egg" },
		{ id = "j_egg" },
		{ id = "j_egg", edition = "foil", eternal = true },
	},
	consumeables = {
		{ id = "c_sigil" },
	},
	vouchers = {
		{ id = "v_hieroglyph" },
	},
	deck = {
		--enhancement = 'm_glass',
		--edition = 'foil',
		--gold_seal = true,
		--yes_ranks = {['3'] = true,T = true},
		--no_ranks = {['4'] = true},
		--yes_suits = {S=true},
		--no_suits = {D=true},
		cards = {
			{ s = "D", r = "2", e = "m_glass" },
			{ s = "D", r = "3", e = "m_glass" },
			{ s = "D", r = "4", e = "m_glass" },
			{ s = "D", r = "5", e = "m_glass" },
			{ s = "D", r = "6", e = "m_glass" },
			{ s = "D", r = "7", e = "m_glass" },
			{ s = "D", r = "8", e = "m_glass" },
			{ s = "D", r = "9", e = "m_glass" },
			{ s = "D", r = "T", e = "m_glass" },
			{ s = "D", r = "J", e = "m_glass" },
			{ s = "D", r = "Q", e = "m_glass" },
			{ s = "D", r = "K", e = "m_glass" },
			{ s = "D", r = "A", e = "m_glass" },
			{ s = "C", r = "2", e = "m_glass" },
			{ s = "C", r = "3", e = "m_glass" },
			{ s = "C", r = "4", e = "m_glass" },
			{ s = "C", r = "5", e = "m_glass" },
			{ s = "C", r = "6", e = "m_glass" },
			{ s = "C", r = "7", e = "m_glass" },
			{ s = "C", r = "8", e = "m_glass" },
			{ s = "C", r = "9", e = "m_glass" },
			{ s = "C", r = "T", e = "m_glass" },
			{ s = "C", r = "J", e = "m_glass" },
			{ s = "C", r = "Q", e = "m_glass" },
			{ s = "C", r = "K", e = "m_glass" },
			{ s = "C", r = "A", e = "m_glass" },
			{ s = "H", r = "2", e = "m_glass" },
			{ s = "H", r = "3", e = "m_glass" },
			{ s = "H", r = "4", e = "m_glass" },
			{ s = "H", r = "5", e = "m_glass" },
			{ s = "H", r = "6", e = "m_glass" },
			{ s = "H", r = "7", e = "m_glass" },
			{ s = "H", r = "8", e = "m_glass" },
			{ s = "H", r = "9", e = "m_glass" },
			{ s = "H", r = "T", e = "m_glass" },
			{ s = "H", r = "J", e = "m_glass" },
			{ s = "H", r = "Q", e = "m_glass" },
			{ s = "H", r = "K", e = "m_glass" },
			{ s = "H", r = "A", e = "m_glass" },
			{ s = "S", r = "2", e = "m_glass" },
			{ s = "S", r = "3", e = "m_glass" },
			{ s = "S", r = "4", e = "m_glass" },
			{ s = "S", r = "5", e = "m_glass" },
			{ s = "S", r = "6", e = "m_glass" },
			{ s = "S", r = "7", e = "m_glass" },
			{ s = "S", r = "8", e = "m_glass" },
			{ s = "S", r = "9", e = "m_glass" },
			{ s = "S", r = "T", e = "m_glass" },
			{ s = "S", r = "J", e = "m_glass" },
			{ s = "S", r = "Q", e = "m_glass" },
			{ s = "S", r = "K", e = "m_glass" },
			{ s = "S", r = "A", e = "m_glass" },
		},
		type = "Challenge Deck",
	},
	restrictions = {
		banned_cards = {
			{ id = "j_joker" },
			{ id = "j_egg" },
		},
		banned_tags = {
			{ id = "tag_garbage" },
			{ id = "tag_handy" },
		},
		banned_other = {
			{ id = "bl_wall", type = "blind" },
		},
	},
})
